travis:
  secure:
    BINSTAR_TOKEN: KC3JsqkVYw4cd2hOtTjBKp1BV0exdQaU/zODpaFa1uFXfdg65HQE52FJiZIB6TL2Ijs80qXaREtl33HHybhnQFL3wITW3cPTUWlUPhNHZ2PNYFxkg97+gyCDL8THiZWof89CS7BSP24l+GRzV1wbkJz7Te9OgwJ8fV9yKgBd0HrAtxrhVb/62y7VFnfErpAr8TkHY5VD25/6MlOW7xmLDzA76uooJJJp6Y7C5WhBcY9I7v9hxK4d5l8Ub1zbvTx2b1BNpPzAaDUt2cKmCFrDKcjJonzIElPoLI/xSmOrwxBTMdoZWguLiCs/94ceO6VXyu46u76QB8mxct8i/kHJRntWXy6rZDadpVdgcLB2SizmoKNLGHXlign0xmRzmtlY2XRXJMcWhlVkkNgzBHCb8ExdmsumK4S00ucU6gKElsitJINCYaUwTqDXYrZ1nwq+Q71iLqWIbhj0aKpgJDVRZ0zFuZpYgzbnhsQzdXO5lAjA5TU3CmdNcQtb2frCFdLqWX03tI9s2kVqV4eTGti5Ukqh7sM0kCxaVlFF+G/5fLthck100qUCBiDRWUzTuHoBzT/YTwX27kU4PMuopyJCidts6MqETLR4vVQK7Igooatqm9e52tWxBbbXvmGe5XzYuVXfMNlQf2slkFfZcMABnwLqOG1V8KjN2dTZ+z2v5B8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
