appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: DTQtz9jokXADNDMmqpiUWkABknsf2nfq/QdywtKx0SQ1gTih04KoQy8fzgrMQLmpRhIqCigqYMsdrjzh3OWMEuTIhRT5DExk0XNAckOB/ZO0qRC3gmrvQNQ96foH5loFzYGSLgYT4iR2gDRgtU0Vrl2pczNvVTT4i7OSML0ucYmsG5tYyzi+lXKntZ7aPbW98mxR1oPutuYkizPOOJFmwoG+uEXzEBo+DsG+Lz9Dym8zw4uO8WqtLCnToMzA2k+ADiHmip5Ob99zgl6HMTfLLPXOi+OHkquNrTH5/Sb4cKSPwkodnF/isOGTHsPy9xrmo/gPVgKwm1lMvvEZ3C/MErDUDJT0R33xqdZXyWgmnC/NY4E3vFkEsPc8crCKTGfsJN+MhTRu+rELHGaQXQHi6dTNpZ96eUzITHyOG8oTuY0Im0Bk/4rFVn8uSEVmG+N2wuGDgmf9WoPoEcLuWJnufmwqzhc8wbfX3QY7ARW5uIWSEv0DXKnj1L46/LvZkenk0gcZPZxgeiyAUgWsQ2+q+9Ge4tvCRUuSYPM4IWf58SPN29RX8i3HK5rp+QN7Q1M9qeT5bxOiaMIRM5m0mhlrkxJIulddlaDklta0eKAeZ7mR8n+OzYM25epvqPYEPfHqX4nB1QARZcLxfdNSuBzjsr5292wLzZnD6Jvidqu8mAI=}
