travis:
  secure:
    BINSTAR_TOKEN: thL6Vc2O11xCIIii12JCufabxKJ/Mg+Xvutdxtv6R2pMkZgzAmb9NE7vVmCacyEYyFg8qSXI9JBy/8sLb8e3tgACx05nUpN0Eg0GtXGkkhdG/7/RwBPEysHDGnr2772t1iMmQk9djuMbdoPV8YqkC6qpDBbo/AF7vN2TQ7qUh9eFmsQsKSKAIXhq4JhP07mMztoHLZ+P7xxzZN/UE05Mhql94pL4KR0a6fgdVW4T34sezAlvgyTXOA5G6HVzhsUSDaiQbSnON2uyx7d76pF/omM/QJv8EO2h+RmqH5hLS1WxD10tftjoBaExNFCCKdeos/uPFoobOmE2MWDwsSDI+1x2/OpYZmlkpPb0a2iGFgJaxiMWTZdfcywMudUxELieAtDyiYTC8xgWsjj5DB46qBaFUD2d2dQGm+7A37I0y+syFK1HCGbkq3zeUzzZlEazEXPAf5kNNokJhzhZlfr9rrgtwNPxCzEfNYX5ScyAjlQw/XjiiwtAQnkl8U7AMXD/ddICHVd3HLqZtMBPuiND9lwUZRq8vM0kqK2QM6xYLEhvQXQ+zg6h1g6oj8vBV9q+dTNlgUz8g7uUI5WPRy3K+Azjl3MRuw/fGs54FdkmE/knvo/iqyZjysmSgsH28V+NEcgOUFy5qAFteIgsvGYgQ3OJRCcQfnO1qrIXGSNQxM0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
