travis:
  secure:
    BINSTAR_TOKEN: Xf2zc96k1E68fYvxrjIqSpQlwr0XE2F3c/+QwsHDp66zzzf8O4532ETfxC5oBTYtj7baT3jlfrkrCgki02u6F8CPzbpcevU6zQNmaVbTmz/U5SeJXj8bU+HO4zzhwHwmFQX8hsE18564T9OeT1hApKJ7dx7wcf+Xzjbbt5QmOz44we0fhtG5uiSZ5ho0h74+rIw3KNIVSXemp+L42aEWw7yKznRs4VSpdzyLnmfeELUn6VefoS6mF7OZtBUON57h7Lx3kMJpwrGFz4SBTEwSO9hNnbfB0bBxceOaD04vnMmKFwz9lHyDZex5u4G0u6WOHycMYrouz+TlbwCks5/DOCZSTp6p/NiU9Q06EBebWD3KnKDJFxwJj7PNCFTt5Vhq/mlPdimJM1LV/Ljf5e5eWvmQ1p8XcVZqO4j9UifiMdoPSvlA1gSyeAbuRQTf6fc1KzL2UMq9iv7u4Ztywz4Du64cTei9kLVirdQNNYQVXX4q0XaQ8+9PyaQNeQKea9qKIs8tviu0t9Mv7xcK/HyNUFBaaxjpNIbkCB+jIP3+iIDS1dL38+MSPHLLXQmp2NhsQ8swMgg00hXaFasXyORqcR3pojRcAqgBsoZd8iWV5GTeBuoeqcH5ARwMnGjfE9udFDCeiMauG2o3F0lgfJpCv6BEMLW6Ls9c3VNRG6Zoq74=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
